### ISSUE TITLE
using the same procces for chat

### ISSUE THREAD

**Issue by NagWolf** [mcphee11/genesys-cloud-voice-survey#1]
Hi Want to find out if the same process will work for chat and want to confirm the data actions to post the survey results is it a post or put  function as I am not able to find the post one on the development API explorer

**Comment by mcphee11** [comment]
I have another repo on how I have done this in the past for webMessenger. Although it's prob over due for an update as now U don't need to make Ur own "toaster" there is a newer API you can use. It will still work as is. You could also use questions conversationally and then POST to the survey like I have here in voice. There are options, these examples just show some possibilities.
